name: mhnfs
encoder:
  activation: selu
  input_dim: 2248
  number_hidden_layers: 0
  number_hidden_neurons: 1024
  regularization:
    input_dropout: 0.1
    dropout: 0.5
layerNormBlock:
  usage: True
  affine: False
transformer:
  activity_embedding_dim: 64
  number_heads: 8
  dim_forward: 567
  dropout: 0.5
  num_layers: 1
hopfield:
  dim_QK: 512
  heads: 8
  beta: 0.044194173824159216
  dropout: 0.5
prediction_scaling: 0.044194173824159216
associationSpace_dim: 1024
similarityModule:
  type: cosineSim
  l2Norm: False
  scaling: 1/sqrt(N)
training:
  optimizer: AdamW
  batch_size: 512
  lr: 0.00001
  weightDecay: 0.
  lrScheduler:
    usage: True

